services:
  app:
    build: .
    ports:
      - "12000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: npm run dev
    environment:
      - WATCHPACK_POLLING=true
volumes:
  node_modules:
